# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nawraskitchen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nawraskitchen
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
